#!/usr/bin/env node
// scripts/merge-cards.mjs
// Merges all 8 source files in src/data/source/ into src/data/cards.js
// Run before build: node scripts/merge-cards.mjs
// Also called by GitHub Actions deploy.yml before `npm run build`

import { writeFileSync, existsSync } from 'fs';
import { pathToFileURL } from 'url';
import path from 'path';

const ROOT   = process.cwd();
const SOURCE = path.join(ROOT, 'src', 'data', 'source');
const OUTPUT = path.join(ROOT, 'src', 'data', 'cards.js');

const SOURCES = [
  { file: 'cards-common.js',         name: 'CARDS_COMMON' },
  { file: 'cards-common-vocab.js',   name: 'CARDS_COMMON_VOCAB' },
  { file: 'cards-lifeline.js',       name: 'CARDS_LIFELINE' },
  { file: 'cards-lifeline-vocab.js', name: 'CARDS_LIFELINE_VOCAB' },
  { file: 'cards-kenchiku.js',       name: 'CARDS_KENCHIKU' },
  { file: 'cards-kenchiku-vocab.js', name: 'CARDS_KENCHIKU_VOCAB' },
  { file: 'cards-doboku.js',         name: 'CARDS_DOBOKU' },
  { file: 'cards-doboku-vocab.js',   name: 'CARDS_DOBOKU_VOCAB' },
];

// Verify all source files exist
for (const { file } of SOURCES) {
  const fullPath = path.join(SOURCE, file);
  if (!existsSync(fullPath)) {
    console.error(`❌ Missing source file: src/data/source/${file}`);
    console.error('   Run `node scripts/split-cards.mjs` first.');
    process.exit(1);
  }
}

// Load all arrays
const allCards = [];
for (const { file, name } of SOURCES) {
  const mod = await import(pathToFileURL(path.join(SOURCE, file)));
  const cards = mod[name];
  if (!Array.isArray(cards)) {
    console.error(`❌ ${file} does not export ${name} as an array`);
    process.exit(1);
  }
  allCards.push(...cards);
  console.log(`  ✓ ${file.padEnd(30)} ${cards.length} cards`);
}

// Restore original order using _origIndex, then strip it before output
const hasIndex = allCards.every(c => typeof c._origIndex === 'number');
if (hasIndex) {
  allCards.sort((a, b) => a._origIndex - b._origIndex);
}

// Strip _origIndex from output (it's an internal merge artifact)
const outputCards = allCards.map(({ _origIndex, ...card }) => card);

function serializeCard(card) {
  const pairs = Object.entries(card)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join(', ');
  return `  { ${pairs} }`;
}

const header = [
  `// src/data/cards.js — AUTO-GENERATED. Do not edit directly.`,
  `// Edit files in src/data/source/ instead.`,
  `// Generated by: node scripts/merge-cards.mjs`,
  `// Total cards: ${outputCards.length}`,
  ``,
  `export const CARDS = [`,
].join('\n');

writeFileSync(OUTPUT, header + '\n' + outputCards.map(serializeCard).join(',\n') + '\n];\n', 'utf8');

console.log(`\n✅ Merged ${outputCards.length} cards → src/data/cards.js`);
